/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistema_de_monitoramento_ambiental_1.pkg0;

import static java.awt.image.ImageObserver.HEIGHT;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author lucas
 */
public class NovaEspecie extends javax.swing.JFrame {
    
    AreaProtegida pa = new AreaProtegida();
    String nomeCientifico;
    String nomePopular;
    String categoria;
    
    public NovaEspecie() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalvarE = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextAreaE = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TfNomeC = new javax.swing.JTextField();
        TfNomeP = new javax.swing.JTextField();
        btnSairE = new javax.swing.JButton();
        btnDadosE = new javax.swing.JButton();
        TfCategoria = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Especies");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalvarE.setBackground(new java.awt.Color(0, 153, 102));
        btnSalvarE.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        btnSalvarE.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvarE.setText("Salvar");
        btnSalvarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarEActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvarE, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 259, 103, -1));

        TextAreaE.setEditable(false);
        TextAreaE.setColumns(20);
        TextAreaE.setRows(5);
        jScrollPane1.setViewportView(TextAreaE);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, -1, 205));

        jLabel1.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 102));
        jLabel1.setText("Categoria de Risco:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        jLabel2.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 102));
        jLabel2.setText("Nome Popular:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 102));
        jLabel3.setText("Nome Cientifico:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));
        getContentPane().add(TfNomeC, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 270, -1));
        getContentPane().add(TfNomeP, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 270, -1));

        btnSairE.setBackground(new java.awt.Color(0, 153, 102));
        btnSairE.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        btnSairE.setForeground(new java.awt.Color(255, 255, 255));
        btnSairE.setText("Sair");
        btnSairE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairEActionPerformed(evt);
            }
        });
        getContentPane().add(btnSairE, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 150, -1));

        btnDadosE.setBackground(new java.awt.Color(0, 153, 102));
        btnDadosE.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        btnDadosE.setForeground(new java.awt.Color(255, 255, 255));
        btnDadosE.setText("Mostrar Especies");
        btnDadosE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDadosEActionPerformed(evt);
            }
        });
        getContentPane().add(btnDadosE, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, 150, -1));

        TfCategoria.setBackground(new java.awt.Color(0, 153, 102));
        TfCategoria.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        TfCategoria.setForeground(new java.awt.Color(255, 255, 255));
        TfCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vunerável", "Em Perigo" }));
        getContentPane().add(TfCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 240, -1));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 290, 60));

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 290, 60));

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 290, 60));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistema_de_monitoramento_ambiental_1/pkg0/imagens/Captura de tela 2024-10-28 232641.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 630, 350));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarEActionPerformed
        nomeCientifico = String.valueOf(TfNomeC.getText());
        nomePopular = String.valueOf(TfNomeP.getText());
        categoria = String.valueOf(TfCategoria.getSelectedItem().toString());  // para pegar dados da comboBox
        TextAreaE.append("Nome Cientifico: \t" + nomeCientifico + "\n");
        TextAreaE.append("Nome Popular: \t" + nomePopular + "\n");
        TextAreaE.append("Categoria: \t" + categoria + "\n \n" );
        pa.adicionarEspecie(nomeCientifico, nomePopular, categoria);
        ImageIcon icon = new ImageIcon("C:\\Users\\lucas\\OneDrive\\Documentos\\aprendendo java\\ListaLTt\\src\\sistema_de_monitoramento_ambiental_1\\pkg0\\imagens\\verificar.png");
        JOptionPane.showMessageDialog(null, "Especie cadastrada com sucesso.","",HEIGHT, icon);
        TfNomeC.setText("");
        TfNomeP.setText("");
        TfNomeC.requestFocus();

    }//GEN-LAST:event_btnSalvarEActionPerformed

    private void btnSairEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairEActionPerformed
        //System.exit(0);
        this.dispose();
    }//GEN-LAST:event_btnSairEActionPerformed

    private void btnDadosEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDadosEActionPerformed

        pa.listarEspecie();
        ImageIcon icon = new ImageIcon("C:\\Users\\lucas\\OneDrive\\Documentos\\aprendendo java\\ListaLTt\\src\\sistema_de_monitoramento_ambiental_1\\pkg0\\imagens\\biodegradavel.png");
        JOptionPane.showMessageDialog(rootPane, TextAreaE.getText(), "Especies", HEIGHT, icon);
    }//GEN-LAST:event_btnDadosEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovaEspecie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovaEspecie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovaEspecie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovaEspecie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NovaEspecie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TextAreaE;
    private javax.swing.JComboBox<String> TfCategoria;
    private javax.swing.JTextField TfNomeC;
    private javax.swing.JTextField TfNomeP;
    private javax.swing.JButton btnDadosE;
    private javax.swing.JButton btnSairE;
    private javax.swing.JButton btnSalvarE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
