/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistema_de_monitoramento_ambiental_1.pkg0;

import javax.swing.JOptionPane;

/**
 *
 * @author lucas
 */
public class NovoRelatorio extends javax.swing.JFrame {
    ProjetoAmbiental pa = new ProjetoAmbiental();
    String data;
    String responsavel;
    String conteudo;
    
    public NovoRelatorio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TextRelatorio = new javax.swing.JTextArea();
        TfConteudo = new javax.swing.JTextField();
        TfData = new javax.swing.JTextField();
        TfResp = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnDados1 = new javax.swing.JButton();
        btnSalvar1 = new javax.swing.JButton();
        btnSair1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Relatorios");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextRelatorio.setColumns(20);
        TextRelatorio.setRows(5);
        jScrollPane1.setViewportView(TextRelatorio);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 230, 200));
        getContentPane().add(TfConteudo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 270, -1));
        getContentPane().add(TfData, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 270, -1));
        getContentPane().add(TfResp, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 270, -1));

        jLabel1.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 102));
        jLabel1.setText("Responsavel:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jLabel2.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 102));
        jLabel2.setText("Data:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, 20));

        jLabel3.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 102));
        jLabel3.setText("Conteudo:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        btnDados1.setBackground(new java.awt.Color(0, 153, 102));
        btnDados1.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        btnDados1.setForeground(new java.awt.Color(255, 255, 255));
        btnDados1.setText("Mostrar Relatorios");
        btnDados1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDados1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnDados1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, 130, -1));

        btnSalvar1.setBackground(new java.awt.Color(0, 153, 102));
        btnSalvar1.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        btnSalvar1.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar1.setText("Salvar");
        btnSalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 103, -1));

        btnSair1.setBackground(new java.awt.Color(0, 153, 102));
        btnSair1.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        btnSair1.setForeground(new java.awt.Color(255, 255, 255));
        btnSair1.setText("Sair");
        btnSair1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSair1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 130, -1));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 290, 60));

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 290, 60));

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 290, 60));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistema_de_monitoramento_ambiental_1/pkg0/imagens/Captura de tela 2024-10-28 232641.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 350));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDados1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDados1ActionPerformed
        pa.listarRelatorios();
        JOptionPane.showMessageDialog(rootPane, TextRelatorio.getText());

    }//GEN-LAST:event_btnDados1ActionPerformed

    private void btnSalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvar1ActionPerformed
        data = TfData.getText();
        responsavel = TfResp.getText();
        conteudo = TfConteudo.getText();
        TextRelatorio.append("Data: \t" + data + "\n");
        TextRelatorio.append("Responsavel: \t" + responsavel + "\n");
        TextRelatorio.append("Conteudo: \t" + conteudo + "\n \n" );
        pa.adicionarRelatorio(data, responsavel, conteudo);

        JOptionPane.showMessageDialog(null, "Relatorio cadastrado com sucesso.");
        TfData.setText("");
        TfResp.setText("");
        TfConteudo.setText("");
        TfData.requestFocus();
    }//GEN-LAST:event_btnSalvar1ActionPerformed

    private void btnSair1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSair1ActionPerformed
        //System.exit(0);
        this.dispose();
    }//GEN-LAST:event_btnSair1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovoRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovoRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovoRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovoRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NovoRelatorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TextRelatorio;
    private javax.swing.JTextField TfConteudo;
    private javax.swing.JTextField TfData;
    private javax.swing.JTextField TfResp;
    private javax.swing.JButton btnDados1;
    private javax.swing.JButton btnSair1;
    private javax.swing.JButton btnSalvar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
